meta_product_name: "Buddy'nGo"
meta_title: "Buddy'nGo - Get the fun out of your buddies! Only the fun."
meta_description: "Facilitate the decision-making of your group trips : Create your trip, invite your firends, and let the magic happen!"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards

